# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20160725_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='desctiption',
            new_name='description',
        ),
    ]
